name: Laravel autodiscovery lock CI

on: [push, pull_request]

jobs:
  check-8.1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
          uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress

      - name: Execute tests (Unit tests) via PHPUnit
        run: |
          vendor/bin/phpstan
  check-8.0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
          uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress

      - name: Execute tests (Unit tests) via PHPUnit
        run: |
          vendor/bin/phpstan
  check-7.4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
          uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress

      - name: Execute tests (Unit tests) via PHPUnit
        run: |
          vendor/bin/phpstan
